// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kutuphane24.Models;

namespace kutuphane24.Migrations
{
    [DbContext(typeof(KutuphaneDBContext))]
    [Migration("20211115153707_KutuphaneDB")]
    partial class KutuphaneDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Turkish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kutuphane24.Models.TblCezalar", b =>
                {
                    b.Property<int>("CezaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CezaID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Başlangıç")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("Bitiş")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("Hareket")
                        .HasColumnType("int");

                    b.Property<decimal?>("Para")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Uye")
                        .HasColumnType("int");

                    b.HasKey("CezaId");

                    b.HasIndex("Hareket");

                    b.HasIndex("Uye");

                    b.ToTable("TblCezalar");
                });

            modelBuilder.Entity("kutuphane24.Models.TblHareket", b =>
                {
                    b.Property<int>("HareketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HareketID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AlısTarih")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("Kitap")
                        .HasColumnType("int");

                    b.Property<int?>("Personel")
                        .HasColumnType("int");

                    b.Property<int?>("Uye")
                        .HasColumnType("int");

                    b.Property<DateTime?>("İadeTarih")
                        .HasColumnType("smalldatetime");

                    b.HasKey("HareketId");

                    b.HasIndex("Kitap");

                    b.HasIndex("Uye");

                    b.ToTable("TblHareket");
                });

            modelBuilder.Entity("kutuphane24.Models.TblKasa", b =>
                {
                    b.Property<int>("KasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KasaID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ay")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("KasaId");

                    b.ToTable("TblKasa");
                });

            modelBuilder.Entity("kutuphane24.Models.TblKategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KategoriID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KategoriAd")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength(true);

                    b.HasKey("KategoriId");

                    b.ToTable("TblKategori");
                });

            modelBuilder.Entity("kutuphane24.Models.TblKitap", b =>
                {
                    b.Property<int>("KitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KitapID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BasimYil")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength(true);

                    b.Property<bool?>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("Sayfa")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("YayinEvi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Yazar")
                        .HasColumnType("int");

                    b.HasKey("KitapId");

                    b.HasIndex("Kategori");

                    b.HasIndex("Yazar");

                    b.ToTable("TblKitap");
                });

            modelBuilder.Entity("kutuphane24.Models.TblPersonel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonelID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Personel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PersonelId");

                    b.ToTable("TblPersonel");
                });

            modelBuilder.Entity("kutuphane24.Models.TblUye", b =>
                {
                    b.Property<int>("UyeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UyeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AD");

                    b.Property<string>("Fotograf")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Mail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Okul")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sifre")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Soyad")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UyeId");

                    b.ToTable("TblUye");
                });

            modelBuilder.Entity("kutuphane24.Models.TblYazar", b =>
                {
                    b.Property<int>("YazarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("YazarID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Detay")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Soyad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("YazarId");

                    b.ToTable("TblYazar");
                });

            modelBuilder.Entity("kutuphane24.Models.VwKitap", b =>
                {
                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BasimYil")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength(true);

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("KategoriAd")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength(true);

                    b.Property<int>("KitapId")
                        .HasColumnType("int")
                        .HasColumnName("KitapID");

                    b.Property<string>("Sayfa")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("YayinEvi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("YazarAdi")
                        .HasMaxLength(61)
                        .IsUnicode(false)
                        .HasColumnType("varchar(61)");

                    b.ToView("VW_Kitap");
                });

            modelBuilder.Entity("kutuphane24.Models.TblCezalar", b =>
                {
                    b.HasOne("kutuphane24.Models.TblHareket", "HareketNavigation")
                        .WithMany("TblCezalars")
                        .HasForeignKey("Hareket")
                        .HasConstraintName("FK_TblCezalar_TblHareket");

                    b.HasOne("kutuphane24.Models.TblUye", "UyeNavigation")
                        .WithMany("TblCezalars")
                        .HasForeignKey("Uye")
                        .HasConstraintName("FK_TblCezalar_TblUye");

                    b.Navigation("HareketNavigation");

                    b.Navigation("UyeNavigation");
                });

            modelBuilder.Entity("kutuphane24.Models.TblHareket", b =>
                {
                    b.HasOne("kutuphane24.Models.TblKitap", "KitapNavigation")
                        .WithMany("TblHarekets")
                        .HasForeignKey("Kitap")
                        .HasConstraintName("FK_TblHareket_TblKitap");

                    b.HasOne("kutuphane24.Models.TblUye", "UyeNavigation")
                        .WithMany("TblHarekets")
                        .HasForeignKey("Uye")
                        .HasConstraintName("FK_TblHareket_TblUye");

                    b.Navigation("KitapNavigation");

                    b.Navigation("UyeNavigation");
                });

            modelBuilder.Entity("kutuphane24.Models.TblKitap", b =>
                {
                    b.HasOne("kutuphane24.Models.TblKategori", "KategoriNavigation")
                        .WithMany("TblKitaps")
                        .HasForeignKey("Kategori")
                        .HasConstraintName("FK_TblKitap_TblKategori");

                    b.HasOne("kutuphane24.Models.TblYazar", "YazarNavigation")
                        .WithMany("TblKitaps")
                        .HasForeignKey("Yazar")
                        .HasConstraintName("FK_TblKitap_TblYazar");

                    b.Navigation("KategoriNavigation");

                    b.Navigation("YazarNavigation");
                });

            modelBuilder.Entity("kutuphane24.Models.TblHareket", b =>
                {
                    b.Navigation("TblCezalars");
                });

            modelBuilder.Entity("kutuphane24.Models.TblKategori", b =>
                {
                    b.Navigation("TblKitaps");
                });

            modelBuilder.Entity("kutuphane24.Models.TblKitap", b =>
                {
                    b.Navigation("TblHarekets");
                });

            modelBuilder.Entity("kutuphane24.Models.TblUye", b =>
                {
                    b.Navigation("TblCezalars");

                    b.Navigation("TblHarekets");
                });

            modelBuilder.Entity("kutuphane24.Models.TblYazar", b =>
                {
                    b.Navigation("TblKitaps");
                });
#pragma warning restore 612, 618
        }
    }
}
